version: "3"

services:
  api:
    build: ./api/
    ports: 
      - "8000:8000"
    volumes:
      - ./api:/usr/src/app
      - ./config/certs:/usr/src/app/certs:ro
    environment:
      - DATABASE_URL=postgres://dev_user:dev_password@db:5432/user_db
    links:
      - db
    command: bash -c "diesel setup && cargo watch -x run"
    depends_on: 
      db:
        condition: service_healthy

  db:
    image: "postgres:latest"
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./config/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}